apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kbit-devops-test
spec:
  destinations:
  - namespace: kbit-devops-test
    server: https://kubernetes.default.svc
  sourceRepos:
  -
  clusterResourceWhitelist:
  - group: 'project.openshift.io'
    kind: Project
  - group: ''
    kind: Namespace