apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kbit-devops-dev
spec:
  destinations:
  - namespace: kbit-devops-dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: 'project.openshift.io'
    kind: Project
  sourceRepos:
  - git@github.com:Dimss/kbit-gitops.git