kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - insecure: true
      insecureIgnoreHostKey: true
#      sshPrivateKeySecret:
#        key: sshPrivateKey
#        name: repo-gitops-infra
      url: "https://github.com/Dimss/gitops-infra.git"
    - insecure: true
      insecureIgnoreHostKey: true
#      sshPrivateKeySecret:
#        key: sshPrivateKey
#        name: repo-kbit-devops
      url: "https://github.com/Dimss/kbit-gitops.git"
  resource.customizations: |
    route.openshift.io/Route:
      ignoreDifferences: |
        jsonPointers:
        - /status/ingress
